- title: Car Hacking Village
  url: https://virtualappsecindonesia2020.sched.com/event/f6QA/car-hacking-village
  trainers: Jay Turla (Bugcrowd)
  duration: 6 Hours
  days: Sun
  localprice: 10250 NIS
  price: $2400
- title: Creating a Secret Room in the DarkWeb
  trainers: Danny Ismarianto Ruhiyat (CIKUR)
  duration: 6 hours
  days: Sun
  localprice: 10250 NIS
  price: $2400
  url: https://virtualappsecindonesia2020.sched.com/event/f6SN/creating-a-secret-room-in-the-darkweb
- title: Advanced Whiteboard hacking – aka hands-on  Threat Modeling
  url: https://globalappsectelaviv2019.sched.com/event/MEj7/advanced-whiteboard-hacking-aka-hands-on-threat-modeling
  trainers: Steven Wierckx (Toreon)
  duration: 6 Hours
  days: Mon/Tue
  localprice: 7050 NIS
  price: $1650
- title: Kubernetes Overview and exploitation
  url: https://virtualappsecindonesia2020.sched.com/event/fATl/kubernetes-overview-and-exploitation
  trainers: Mihir Shah (Awake Security)
  duration: 6 hours
  days: Sun
  localprice: 7050 NIS
  price: $1650
- title: Hands on Threat Hunting workshop
  url: https://virtualappsecindonesia2020.sched.com/event/f6TP/hands-on-threat-hunting-workshop
  trainers: Manieendar Mohan and Rejah Rehim (Beagle Cyber Innovations)
  duration: 6 hours
  days: Sun
  localprice: 7050 NIS
  price: $1650
- title: Building Scalable Labs for Offensive and Defensive Security Scenarios
  url: https://virtualappsecindonesia2020.sched.com/event/f6QO/building-scalable-labs-for-offensive-and-defensive-security-scenarios
  trainers: Omar Santos (Cisco)
  duration: 6 hours
  days: Sun
  localprice: 7050 NIS
  price: $1650
