- title: Car Hacking Village
  url: https://virtualappsecindonesia2020.sched.com/event/f6QA/car-hacking-village
  trainers: Jay Turla (Bugcrowd)
  duration: 6 hours
  days: Sun
  localprice:
  price: 
- title: Creating a 'Secret Room' in the DarkWeb
  trainers: Danny Ismarianto Ruhiyat (CIKUR)
  duration: 6 hours
  days: Sun
  localprice: 
  price:
  url: https://virtualappsecindonesia2020.sched.com/event/f6SN/creating-a-secret-room-in-the-darkweb
- title: CyberWarOps Training: Red and Blue Team Joint Operations
  url: https://virtualappsecindonesia2020.sched.com/event/f6PE/cyberwarops-training-red-and-blue-team-joint-operations
  trainers: Manish Gupta (Citrix) and Yash Bharadwaj (CyberWarFare Labs)
  duration: 6 hours
  days: Sun
  localprice:
  price: 
- title: Kubernetes Overview and exploitation
  url: https://virtualappsecindonesia2020.sched.com/event/fATl/kubernetes-overview-and-exploitation
  trainers: Mihir Shah (Awake Security)
  duration: 6 hours
  days: Sun
  localprice: 
  price: 
- title:  Hands on Threat Hunting workshop
  url: https://virtualappsecindonesia2020.sched.com/event/f6TP/hands-on-threat-hunting-workshop
  trainers: Manieendar Mohan and Rejah Rehim (Beagle Cyber Innovations)
  duration: 6 hours
  days: Sun
  localprice: 
  price: 
- title:  Building Scalable Labs for Offensive and Defensive Security Scenarios
  url: https://virtualappsecindonesia2020.sched.com/event/f6QO/building-scalable-labs-for-offensive-and-defensive-security-scenarios
  trainers: Omar Santos (Cisco)
  duration: 6 hours
  days: Sun
  localprice: 
  price: 